import { Camera, Mic, Footprints, Thermometer, ArrowLeft, AlertTriangle, Lightbulb, HelpCircle, ShieldAlert, Info, MapPin, Clock, PawPrint } from 'lucide-react';
import { Card, CardHeader } from '@/components/ui/Card';
import { Badge, RiskBadge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { demoReport } from '@/data/mockData';
import { riskScoreColor, riskScoreBarColor } from '@/lib/utils';
import type { Indicator } from '@/types';
import type { PageId } from '@/components/layout/Sidebar';

const severityConfig: Record<Indicator['severity'], { label: string; variant: 'success' | 'warning' | 'danger' }> = {
  normal: { label: 'Normal', variant: 'success' },
  caution: { label: 'Caution', variant: 'warning' },
  critical: { label: 'Critical', variant: 'danger' },
};

function IndicatorRow({ indicator }: { indicator: Indicator }) {
  const { label, variant } = severityConfig[indicator.severity];
  return (
    <div className="flex items-start justify-between gap-4 border-b border-ink-100 py-3 last:border-0">
      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-2">
          <span className="text-sm font-semibold text-ink-800">{indicator.name}</span>
          <Badge variant={variant}>{label}</Badge>
        </div>
        <p className="mt-1 text-sm text-ink-500">{indicator.detail}</p>
      </div>
    </div>
  );
}

function IndicatorSection({
  title,
  icon,
  accent,
  indicators,
}: {
  title: string;
  icon: typeof Camera;
  accent: string;
  indicators: Indicator[];
}) {
  const Icon = icon;
  const criticalCount = indicators.filter((i) => i.severity === 'critical').length;
  const cautionCount = indicators.filter((i) => i.severity === 'caution').length;
  return (
    <Card>
      <CardHeader
        title={title}
        icon={<Icon className="h-4.5 w-4.5" />}
        action={
          <div className="flex gap-1.5">
            {criticalCount > 0 && <Badge variant="danger">{criticalCount} critical</Badge>}
            {cautionCount > 0 && <Badge variant="warning">{cautionCount} caution</Badge>}
            <Badge variant="success">{indicators.length - criticalCount - cautionCount} normal</Badge>
          </div>
        }
      />
      <div className="px-5 py-2">
        {indicators.map((ind, i) => (
          <IndicatorRow key={i} indicator={ind} />
        ))}
      </div>
    </Card>
  );
}

interface ReportPageProps {
  onNavigate: (page: PageId) => void;
}

export function ReportPage({ onNavigate }: ReportPageProps) {
  const report = demoReport;
  const reportAccent = report.overallRiskLevel === 'high-risk' ? 'danger' : report.overallRiskLevel === 'attention' ? 'warning' : 'success';

  return (
    <div className="space-y-5">
      {/* Disclaimer banner */}
      <div className="flex items-start gap-3 rounded-xl border border-warning-200 bg-warning-50 px-4 py-3.5">
        <Info className="mt-0.5 h-5 w-5 shrink-0 text-warning-600" />
        <p className="text-sm text-warning-800">
          <span className="font-semibold">AI-assisted prototype results.</span> This report is generated by an
          experimental analysis system and is <span className="font-semibold">not a veterinary diagnosis</span>.
          Always consult a qualified veterinarian for health decisions.
        </p>
      </div>

      {/* Header card with animal info + risk score */}
      <Card className="overflow-hidden">
        <div className="grid grid-cols-1 lg:grid-cols-3">
          {/* Animal info */}
          <div className="border-b border-ink-100 p-5 lg:border-b-0 lg:border-r">
            <p className="text-xs font-semibold uppercase tracking-wider text-ink-400">Animal Information</p>
            <div className="mt-4 space-y-3">
              <div className="flex items-center gap-2.5">
                <PawPrint className="h-4 w-4 text-brand-500" />
                <span className="font-display text-lg font-bold text-ink-900">{report.animalId}</span>
              </div>
              <div className="flex items-center gap-2.5 text-sm">
                <span className="text-ink-400">Species</span>
                <span className="font-medium text-ink-700">{report.species}</span>
              </div>
              <div className="flex items-center gap-2.5 text-sm">
                <span className="text-ink-400">Age</span>
                <span className="font-medium text-ink-700">{report.age} years</span>
              </div>
              <div className="flex items-center gap-2 text-sm text-ink-600">
                <MapPin className="h-4 w-4 text-ink-400" />
                {report.location}
              </div>
              <div className="flex items-center gap-2 text-sm text-ink-600">
                <Clock className="h-4 w-4 text-ink-400" />
                {report.analyzedAt}
              </div>
            </div>
          </div>

          {/* Risk score gauge */}
          <div className="flex flex-col items-center justify-center border-b border-ink-100 p-5 lg:border-b-0 lg:border-r">
            <p className="text-xs font-semibold uppercase tracking-wider text-ink-400">Risk Score</p>
            <div className="relative mt-4 flex h-32 w-32 items-center justify-center">
              <svg viewBox="0 0 120 120" className="h-full w-full -rotate-90">
                <circle cx="60" cy="60" r="50" fill="none" stroke="#f1f5f9" strokeWidth="10" />
                <circle
                  cx="60"
                  cy="60"
                  r="50"
                  fill="none"
                  stroke={report.overallRiskLevel === 'high-risk' ? '#ef4444' : report.overallRiskLevel === 'attention' ? '#f59e0b' : '#22c55e'}
                  strokeWidth="10"
                  strokeDasharray={`${report.riskScore * 3.14} 314`}
                  strokeLinecap="round"
                  className="transition-all duration-700"
                />
              </svg>
              <div className="absolute inset-0 flex flex-col items-center justify-center">
                <span className={`font-display text-3xl font-bold ${riskScoreColor(report.riskScore)}`}>
                  {report.riskScore}
                </span>
                <span className="text-xs text-ink-400">/ 100</span>
              </div>
            </div>
          </div>

          {/* Overall risk level */}
          <div className="flex flex-col items-center justify-center p-5">
            <p className="text-xs font-semibold uppercase tracking-wider text-ink-400">Overall Risk Level</p>
            <div className="mt-4 flex flex-col items-center gap-3">
              <div className={`flex h-14 w-14 items-center justify-center rounded-2xl ${
                report.overallRiskLevel === 'high-risk' ? 'bg-danger-50 text-danger-600' : 'bg-warning-50 text-warning-600'
              }`}>
                <ShieldAlert className="h-7 w-7" />
              </div>
              <RiskBadge level={report.overallRiskLevel} className="text-sm px-3 py-1.5" />
              <p className="text-center text-xs text-ink-500">
                {report.overallRiskLevel === 'high-risk'
                  ? 'Multiple critical indicators detected. Veterinary review recommended.'
                  : report.overallRiskLevel === 'attention'
                  ? 'Minor indicators present. Monitor closely.'
                  : 'No significant indicators detected.'}
              </p>
            </div>
          </div>
        </div>
      </Card>

      {/* Flag explanation */}
      <Card className="border-warning-200/60">
        <CardHeader
          title="Why was this animal flagged?"
          subtitle="AI-generated explanation of the risk assessment"
          icon={<HelpCircle className="h-4.5 w-4.5" />}
        />
        <div className="p-5">
          <div className="flex gap-3 rounded-lg bg-warning-50/60 p-4">
            <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-warning-600" />
            <p className="text-sm leading-relaxed text-ink-700">{report.flagReason}</p>
          </div>
        </div>
      </Card>

      {/* Indicator sections */}
      <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
        <IndicatorSection
          title="Visual Indicators"
          icon={Camera}
          accent="text-brand-600"
          indicators={report.visualIndicators}
        />
        <IndicatorSection
          title="Audio Indicators"
          icon={Mic}
          accent="text-accent-600"
          indicators={report.audioIndicators}
        />
        <IndicatorSection
          title="Behaviour Indicators"
          icon={Footprints}
          accent="text-blue-600"
          indicators={report.behaviourIndicators}
        />
        <IndicatorSection
          title="Farm-Condition Indicators"
          icon={Thermometer}
          accent="text-teal-600"
          indicators={report.farmConditionIndicators}
        />
      </div>

      {/* Recommended next action */}
      <Card className="border-brand-200/60">
        <CardHeader
          title="Recommended Next Action"
          subtitle="Suggested steps based on the analysis"
          icon={<Lightbulb className="h-4.5 w-4.5" />}
        />
        <div className="p-5">
          <div className="flex gap-3 rounded-lg bg-brand-50/60 p-4">
            <Lightbulb className="mt-0.5 h-5 w-5 shrink-0 text-brand-600" />
            <p className="text-sm leading-relaxed text-ink-700">{report.nextAction}</p>
          </div>
        </div>
      </Card>

      {/* Actions */}
      <div className="flex flex-col items-center gap-3 pb-4 sm:flex-row sm:justify-center">
        <Button
          variant="primary"
          size="lg"
          icon={<ArrowLeft className="h-5 w-5" />}
          onClick={() => onNavigate('dashboard')}
        >
          Return to Dashboard
        </Button>
        <Button
          variant="secondary"
          size="lg"
          onClick={() => onNavigate('assistant')}
        >
          Ask AI Assistant
        </Button>
      </div>

      <p className="text-center text-xs text-ink-400">
        LivestockGuard AI — AI-assisted prototype. This is not a veterinary diagnosis.
      </p>
    </div>
  );
}
